sudo: false
language: python
python: 2.7

before_install:
  - export GALAXY_REPO=https://github.com/galaxyproject/galaxy
  - export GALAXY_RELEASE=release_16.10
  - export PLANEMO_CONDA_PREFIX="$HOME/conda"

install:
  - pip install flake8 planemo
  - planemo conda_init
  - export PATH="$PLANEMO_CONDA_PREFIX/bin:$PATH"
  - |
    conda create -y -q --name hic_conda -c bioconda -c conda-forge \
        numpy scipy matplotlib=1.5.3 nose flake8 pytables biopython samtools=0.1.19 pysam pyBigWig intervaltree
  - . activate hic_conda
  - planemo --version
  - conda --version
  #- python setup.py install
  # Useful for debugging any issues with conda
  - conda info -a

script:
  #- nosetests --with-doctest -sv hicexplorer
  - planemo shed_lint --tools --ensure_metadata --urls --report_level warn --fail_level error --recursive ./galaxy/wrapper
  - planemo conda_install ./galaxy/wrapper
  - planemo test --conda_dependency_resolution --galaxy_branch "$GALAXY_RELEASE" --galaxy_source "$GALAXY_REPO" ./galaxy/wrapper
