sudo: false
language: python
python: 2.7

before_install:
  - export GALAXY_REPO=https://github.com/galaxyproject/galaxy
  - export GALAXY_RELEASE=release_16.10
  - export PLANEMO_CONDA_PREFIX="$HOME/conda"

install:
  - pip install flake8 planemo
  - planemo --version
  - planemo conda_init
  - |
    $PLANEMO_CONDA_PREFIX/bin/conda create -y -q --name hic_conda -c bioconda -c conda-forge
      numpy scipy matplotlib=1.5.3 nose flake8 pytables biopython samtools=0.1.19 pysam pyBigWig intervaltree

script:
  - |
    planemo shed_lint --tools --ensure_metadata --urls
      --report_level warn --fail_level error
      --conda_prefix $PLANEMO_CONDA_PREFIX
      --recursive ./galaxy/wrapper
  - planemo conda_install --conda_prefix $PLANEMO_CONDA_PREFIX ./galaxy/wrapper
  - |
    planemo test --conda_dependency_resolution --galaxy_branch "$GALAXY_RELEASE"
      --conda_prefix $PLANEMO_CONDA_PREFIX
      --galaxy_source "$GALAXY_REPO" ./galaxy/wrapper
  - export PATH="$PLANEMO_CONDA_PREFIX/bin:$PATH"
  - . activate hic_conda
  - conda --version
  - conda info -a
  - python setup.py install
  - nosetests --with-doctest -sv hicexplorer
