language: python
python: 2.7
install:
  - virtualenv .venv
  - . .venv/bin/activate
  - pip install flake8
  - pip install git+git://github.com/maxplanck-ie/HiCExplorer.git@master

script:
  - flake8 . && python -c 'import hicexplorer'
