language: c
sudo: true

env:
  - TRAVIS_PYTHON_VERSION=3.6
  - TRAVIS_PYTHON_VERSION=3.7
os:
  - linux
stages:
  - test

# Setup anaconda
before_install:
  - export HIC_TEST_DATA_DIR="`pwd`/hicexplorer/test/test_data/"
  - export PYTHONWARNINGS="ignore"
  - echo $HIC_TEST_DATA_DIR
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -L https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o miniconda.sh ; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - PATH_WITHOUT_CONDA="$PATH"
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda=4.8 -q
  # - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
# Install packages
install:
  - conda install --yes -c conda-forge -c bioconda python=$TRAVIS_PYTHON_VERSION --file requirements.txt
  - conda install --yes -c conda-forge -c bioconda pytest
  - conda install --yes -c conda-forge -c bioconda nose
  - conda install --yes pathlib
  - conda install --yes -c defaults -c conda-forge -c bioconda configparser
  - python setup.py install
# command to run tests

script:
  - echo 'all good'

jobs:
  include:  
    - stage: test
      os: linux
      env: TRAVIS_PYTHON_VERSION=3.6
      script: py.test hicexplorer/test/trivial_runs/test_hicBuildMatrix_trivial_runs.py
    - stage: test
      os: linux
      env: TRAVIS_PYTHON_VERSION=3.6
      script: py.test hicexplorer/test/trivial_runs/test_hicBuildMatrix_trivial_runs_2.py
    - stage: test
      os: linux
      env: TRAVIS_PYTHON_VERSION=3.6
      script: py.test hicexplorer/test/trivial_runs/test_hicAggregateContacts_trivial_runs.py
    - stage: test
      os: linux
      env: TRAVIS_PYTHON_VERSION=3.6
      script: py.test hicexplorer/test/trivial_runs/test_hicAggregateContacts_trivial_runs_two.py
    - stage: test
      os: linux
      env: TRAVIS_PYTHON_VERSION=3.6
      script: py.test hicexplorer/test/trivial_runs/test_hicAggregateContacts_trivial_runs_three.py
    - stage: test
      os: linux
      env: TRAVIS_PYTHON_VERSION=3.6
      script: travis_wait 40 py.test hicexplorer/test/trivial_runs/test_hicConvertFormat_trivial_runs.py
    - stage: test
      os: linux
      env: TRAVIS_PYTHON_VERSION=3.6
      script: travis_wait 40 py.test hicexplorer/test/trivial_runs/test_hicConvertFormat_trivial_runs_cool.py
    - stage: test
      os: linux
      env: TRAVIS_PYTHON_VERSION=3.7
      script: py.test hicexplorer/test/trivial_runs/test_hicBuildMatrix_trivial_runs.py
    - stage: test
      os: linux
      env: TRAVIS_PYTHON_VERSION=3.7
      script: py.test hicexplorer/test/trivial_runs/test_hicBuildMatrix_trivial_runs_2.py
    - stage: test
      os: linux
      env: TRAVIS_PYTHON_VERSION=3.7
      script: py.test hicexplorer/test/trivial_runs/test_hicAggregateContacts_trivial_runs.py
    - stage: test
      os: linux
      env: TRAVIS_PYTHON_VERSION=3.7
      script: py.test hicexplorer/test/trivial_runs/test_hicAggregateContacts_trivial_runs_two.py
    - stage: test
      os: linux
      env: TRAVIS_PYTHON_VERSION=3.7
      script: py.test hicexplorer/test/trivial_runs/test_hicAggregateContacts_trivial_runs_three.py
    - stage: test
      os: linux
      env: TRAVIS_PYTHON_VERSION=3.7
      script: travis_wait 40 py.test hicexplorer/test/trivial_runs/test_hicConvertFormat_trivial_runs.py
    - stage: test
      os: linux
      env: TRAVIS_PYTHON_VERSION=3.7
      script: travis_wait 40 py.test hicexplorer/test/trivial_runs/test_hicConvertFormat_trivial_runs_cool.py